spring:
  redis:
    host: localhost
    port: 8989

ustawienia:
  numerIndeksu: 461011
  wycena: "CENY_BEZ_ZMIAN"
  zamowienia: "REZERWACJE"
  zaopatrzenie: "POJEDYNCZE"
  wydarzenia: "RAPORT_SPRZEDAŻY"
  liczbaZadan: 200
